version: "3.9"
services:
  db:
    image: postgres:14.1-alpine
    networks:
      - adanet
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ada2025_db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    image: ada2025_app:latest
    networks:
      - adanet
    ports:
      - 5000:5000
    restart: always
    volumes:
      # comment this if you don't want docker-based machines
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      # comment this if you don't want libvirt-based machines
      - type: bind
        source: /var/run/libvirt/libvirt-sock
        target: /var/run/libvirt/libvirt-sock
      # comment this to not share hosts ssh keys
      - type: bind
        source: /root/.ssh
        target: /root/.ssh
    environment:
      - ADA2025_SQLALCHEMY_URL=postgresql://postgres:postgres@db:5432/postgres
      # these are optional, set vars in shell and it will be picked up here
      - ADA2025_MAIL_SENDER=${ADA2025_MAIL_SENDER}
      - ADA2025_MAIL_SERVER=${ADA2025_MAIL_SERVER}
      - ADA2025_MAIL_PORT=${ADA2025_MAIL_PORT}
      - ADA2025_MAIL_USERNAME=${ADA2025_MAIL_USERNAME}
      - ADA2025_MAIL_PASSWORD=${ADA2025_MAIL_PASSWORD}
      - ADA2025_MAIL_USE_TLS=${ADA2025_MAIL_USE_TLS}
      - ADA2025_MAIL_USE_SSL=${ADA2025_MAIL_USE_SSL}
      - ADA2025_SENTRY_DSN=${ADA2025_SENTRY_DSN}
      - ADA2025_SENTRY_ENVIRONMENT=${ADA2025_SENTRY_ENVIRONMENT}
      - ADA2025_FLASK_SECRET_KEY=${ADA2025_FLASK_SECRET_KEY}
      - LOGIN_RECAPTCHA=${LOGIN_RECAPTCHA}
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
      - GOOGLE_OAUTH2_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
      - GOOGLE_OAUTH2_CLIENT_SECRET=${GOOGLE_OAUTH2_CLIENT_SECRET}
      - ADA2025_IRIS_IAM_OAUTH2_CLIENT_ID=${ADA2025_IRIS_IAM_OAUTH2_CLIENT_ID}
      - ADA2025_IRIS_IAM_OAUTH2_CLIENT_SECRET=${ADA2025_IRIS_IAM_OAUTH2_CLIENT_SECRET}

volumes:
  ada2025_db_vol:
networks:
  adanet:
    external: true
